import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {MaleCNSBridge} from '../src/malecns/bridge.js';
import {IntrinsicDrive} from '../src/malecns/motor.js';
import {AdaptiveMotorLearner} from '../src/adaptive/motor_learning.js';
import {decodeGraph} from '../src/malecns/graph.js';import {decodeNeurons} from '../src/malecns/neurons.js';
import {Decoder} from '../src/malecns/rc.js';import {FixedStepper} from '../src/runtime.js';
class WorkerMock{constructor(){this.messages=[];this.dead=false;}postMessage(m){this.messages.push(m);}terminate(){this.dead=true;}}
async function bridge(){globalThis.Worker=WorkerMock;const b=new MaleCNSBridge();await b.load();b.worker.onmessage({data:{type:'ready',epoch:b.epoch}});return b;}
test('worker failure invalidates commands and terminates worker before retry',async()=>{const b=await bridge(),old=b.worker;b.latest={motor:{v:1}};old.onerror({message:'failed'});assert.equal(b.ready,false);assert.equal(b.latest,null);assert(old.dead);await b.load();assert.notEqual(old,b.worker);});
test('ordered batches preserve all 120 sensory ticks without wall-clock throttling',async()=>{const b=await bridge();for(let tick=0;tick<120;tick++){b.setInput({tick,t:tick/120,left:{DM1:tick}});if(b.pending){const id=b.pending.id;assert.equal(b.canAdvance(),false);b.message({type:'activity',epoch:b.epoch,batchId:id,tick,t:tick*1000/120});}}const batches=b.worker.messages.filter(x=>x.type==='batch');assert.equal(batches.length,12);assert.deepEqual(batches.flatMap(x=>x.inputs.map(i=>i.tick)),Array.from({length:120},(_,i)=>i));});
test('stale epochs and late replies cannot release a newer pending batch',async()=>{const b=await bridge();for(let i=0;i<10;i++)b.setInput({tick:i});const old=b.pending.id,epoch=b.epoch;b.reset();for(let i=0;i<10;i++)b.setInput({tick:i});b.message({type:'activity',epoch,batchId:old,motor:{v:1}});assert.equal(b.latest,null);assert(b.pending);});
test('watchdog stops a missing neural acknowledgement',async()=>{const b=await bridge();b.clock=()=>0;for(let i=0;i<10;i++)b.setInput({tick:i});b.clock=()=>10001;assert.equal(b.canAdvance(),false);assert.equal(b.ready,false);assert.equal(b.latest,null);});
test('stepper supports neural backpressure without advancing the body',()=>{const s=new FixedStepper();let n=0;s.advance(.5,()=>{if(n===10)return false;n++;});assert.equal(n,10);s.advance(1/120,()=>n++);assert.equal(n,11);});
test('decoder rejects header-only files and incomplete arithmetic streams',()=>{assert.throws(()=>decodeGraph(new Uint32Array([0x47594c46,1,2,0,1]).buffer));assert.throws(()=>decodeNeurons(new Uint32Array([0x4e594c46,1,2]).buffer));assert.throws(()=>new Decoder(new Uint8Array(4)));});
test('valid small graph decodes and excessive dimensions fail before allocation',()=>{const b=new Uint8Array(40);new Uint32Array(b.buffer,0,5).set([0x47594c46,1,1,0,1]);assert.equal(decodeGraph(b.buffer).N,1);new DataView(b.buffer).setUint32(8,0xffffffff,true);assert.throws(()=>decodeGraph(b.buffer),/budget/);});
test('reset restores intrinsic and adaptive random sequences',()=>{const d=new IntrinsicDrive(5),fresh=new IntrinsicDrive(5);for(let i=0;i<300;i++)d.update(10,{hunger:.9});d.reset();assert.equal(d.left,fresh.left);const a=new AdaptiveMotorLearner({seed:5}),b=new AdaptiveMotorLearner({seed:5});a.update(.1,{});a.reset();a.update(.1,{});b.update(.1,{});assert.deepEqual(a.params(),b.params());});
test('new context discards the previous SPSA comparison window',()=>{const a=new AdaptiveMotorLearner();a.update(.2,{},{contextKey:'floor'});a.update(.1,{},{contextKey:'wall'});assert.equal(a.elapsed,.1);assert.equal(a.generation,0);});
const workerText=fs.readFileSync(new URL('../src/malecns/worker.js',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');
test('worker mode reset clears rate counters and old denominator together',()=>{const messages=[];const c=vm.createContext({self:{postMessage:m=>messages.push(m)},performance:{now:()=>100},setTimeout});vm.runInContext(workerText,c);vm.runInContext("windowCounts[0]=100;windowTypeCounts.set('old',20);setMode('control');",c);assert.equal(vm.runInContext('windowCounts[0]',c),0);assert.equal(vm.runInContext('windowTypeCounts.size',c),0);});
test('worker processes an acknowledged sensor batch in order, using neural time',async()=>{const messages=[],seen=[];const c=vm.createContext({self:{postMessage:m=>messages.push(m)},performance:{now:()=>100},setTimeout,seen});vm.runInContext(workerText,c);vm.runInContext(`net={t:0,p:{dt:.5},nAwake:0,spikeCount:[],setDrive(){},step(){seen.push(input.tick);this.t+=.5;return [];}};groups={ornAll:[],odor:{},sugar:[],contact:[],haltere:[],jo:[],regions:Object.fromEntries(REGION_KEYS.map(k=>[k,[0]]))};regionMask=[];`,c);await vm.runInContext(`runBatch({epoch:0,batchId:1,inputs:Array.from({length:10},(_,i)=>({tick:i,t:i/120,dtMs:1000/120}))})`,c);assert.equal(messages.length,1);assert.equal(messages[0].tick,9);assert.equal(messages[0].t,83);assert.equal(messages[0].hz.AL,0);assert.equal(seen[0],0);assert.equal(seen.at(-1),9);});
