// Bounded, tick-addressed sensory batches with one outstanding acknowledgement.
export class MaleCNSBridge {
 constructor({onStatus,onReady,onActivity,onError,pacing='synchronized'}={}){Object.assign(this,{onStatus,onReady,onActivity,onError});this.worker=null;this.ready=false;this.loading=false;this.info=null;this.latest=null;this.history=[];this.mode='observe';this.epoch=0;this.queue=[];this.pending=null;this.batchId=0;this.lastTick=-1;this.clock=()=>performance.now();this.timeoutMs=10000;this.pacing=pacing==='interactive'?'interactive':'synchronized';this.coalesced=0;this.takeoffReceipt=null;}
 fail(error){this.worker?.terminate();this.worker=null;this.ready=this.loading=false;this.latest=null;this.queue=[];this.pending=null;this.onError?.(error);}
 async load({baseUrl,seed=1}={}){if(this.loading||this.ready)return;this.terminate();this.loading=true;try{const w=this.worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});w.onmessage=e=>{if(this.worker===w)this.message(e.data||{});};w.onerror=e=>{if(this.worker===w)this.fail(new Error(e.message||'MaleCNS worker error'));};w.postMessage({type:'init',baseUrl,seed,epoch:this.epoch});}catch(error){this.fail(error);}}
 message(m){if(m.epoch!==this.epoch)return;if(m.type==='status')this.onStatus?.(m);else if(m.type==='ready'){this.loading=false;this.ready=true;this.info=m;this.onReady?.(m);}else if(m.type==='activity'){if(!this.pending||m.batchId!==this.pending.id)return;this.latest={...m,pacing:this.pacing,coalesced:this.pending.coalesced,receivedAt:this.clock()};this.pending=null;this.history.push({...this.latest,wall:this.clock()});if(this.history.length>1200)this.history.shift();this.onActivity?.(this.latest);if(this.pacing==='interactive')this.flush();}else if(m.type==='error')this.fail(new Error(m.message||'MaleCNS error'));}
 canAdvance(){if(this.pending&&this.clock()-this.pending.at>this.timeoutMs){this.fail(new Error('MaleCNS no respondió al lote sensorial; ensayo pausado.'));return false;}return this.pacing==='interactive'||!this.pending;}
 setInput(input){if(!this.ready||!this.worker)return;if(this.pending&&this.pacing==='synchronized')throw new Error('Body advanced before neural acknowledgement');const tick=input.tick??this.lastTick+1;if(tick<=this.lastTick)throw new Error('Non-monotonic sensory tick');this.lastTick=tick;if(this.queue.length===10){this.queue.shift();this.coalesced++;}this.queue.push({...input,tick,dtMs:1000/120});if(this.queue.length===10)this.flush();}
 flush(){if(!this.ready||!this.queue.length||this.pending)return;const id=++this.batchId;this.pending={id,at:this.clock(),coalesced:this.coalesced};this.worker.postMessage({type:'batch',epoch:this.epoch,batchId:id,inputs:this.queue});this.queue=[];}
 invalidate(){this.epoch++;this.latest=null;this.queue=[];this.pending=null;this.lastTick=-1;this.coalesced=0;this.takeoffReceipt=null;}
 setPacing(value){const next=value==='interactive'?'interactive':'synchronized';if(next===this.pacing)return;this.pacing=next;this.reset();}
 consumeTakeoff(){if(!this.latest?.motor?.takeoffTriggered)return false;const key=`${this.latest.epoch}:${this.latest.batchId}`;if(this.takeoffReceipt===key)return false;this.takeoffReceipt=key;return true;}
 setRunning(value){if(!value)this.flush();}
 setMode(mode){const next=mode==='control'?'control':'observe';if(next===this.mode)return;this.mode=next;this.invalidate();this.history=[];this.worker?.postMessage({type:'mode',mode:next,epoch:this.epoch});}
 reset(){this.invalidate();this.history=[];this.worker?.postMessage({type:'reset',epoch:this.epoch});}
 terminate(){this.worker?.terminate();this.worker=null;this.ready=this.loading=false;this.invalidate();}
 toCSV(){const keys=['AL','MB','CX','SEZ','DN','VNC'];return ['epoch,tick,body_s,neural_ms,mode,source,pacing,coalesced_ticks,'+keys.map(k=>k+'_hz').join(','),...this.history.map(x=>[x.epoch,x.tick,x.bodyTime,x.t,x.mode,'LIF',x.pacing,x.coalesced,...keys.map(k=>Number.isFinite(x.hz?.[k])?x.hz[k]:'')].join(','))].join('\n');}
}
